### PR TITLE
Added codeforuganda

### PR DESCRIPTION
**Pull request by phillipahereza**
Added code for Uganda to the list of countries

### CODE REVIEW

**Comment by DavidLemayian** [comment]
@phillipahereza Could we get a screenshot of what this looks like? :)

**Comment by phillipahereza** [comment]
screen shot 2017-07-14 at 11 27 39

**Comment by phillipahereza** [comment]
@DavidLemayian 
screen shot 2017-07-14 at 11 27 39

**Comment by DavidLemayian** [comment]
@phillipahereza Emm.. the positioning looks off. Probably need
```
<div class="clearfix"></div>
```
before the code you've added.

**Comment by phillipahereza** [comment]
@DavidLemayian fixed 
screen shot 2017-07-14 at 11 51 51

**Pull request merged**
